[package]
name = "how-store-closures-with-actix"
version = "0.1.0"

[dependencies]
log = "~0.4.0"
env_logger = "~0.5.13"
actix = "~0.7.0"
actix-web = { version = "~0.7.8", features = ["tls", "alpn"] }
futures = "~0.1"
